### ISSUE TITLE
console error spam

### ISSUE THREAD

**Issue by NickCloudAT** [NgLoader/Orebfuscator#11]
**Please fill out the following information:**
* Server Version: 1.15.2
* Orebfuscator Version: 4.4.7
* Protocollib Version: 4.5.0

**Describe the bug**
I get the following error spamed in the console.. 

https://pastebin.com/eEwUeyRh

**Comment by marzenie** [comment]
I too ha ve this problem 
https://pastebin.com/5SKVsGYX

**Comment by marzenie** [comment]
( 4.5.0 protocol lib )
oreb 4.4.7
server 1.15.2

**Comment by NgLoader** [comment]
This project is now achived and was moved to [Imprex-Development](https://github.com/Imprex-Development/Orebfuscator)
