### ISSUE TITLE
Issues with Clicking blocks

### ISSUE THREAD

**Issue by Burchard36** [NgLoader/Orebfuscator#4]
Issue: While clicking blocks (Anywhere with first or with item in hand) the players view gets "teleported" around, we deleted orebfuscator and it stopped doing it, installed it again and deleted its folders and we were still getting the issue, the MC Version is 1.15.1 PaperSpigot. If you want me to show you what exactly its doing PM me on discord: Dalton#8402

**Comment by Pratuz** [comment]
@Burchard36 Have you had any news? I have the same problem.

**Comment by Burchard36** [comment]
> 
> 
> @Burchard36 Have you had any news? I have the same problem.

Nothing as of now, we have since remove oreb from our server; I would attempt to fix it but honestly oreb is out of my knowledge for Java

**Comment by NgLoader** [comment]
I commit with a fix soon

**Comment by NgLoader** [comment]
New version [4.4.7](https://github.com/TeamWuffy/Orebfuscator/releases/tag/4.4.7)
