### ISSUE TITLE
isTransparent 

### ISSUE THREAD

**Issue by Foulwerp** [NgLoader/Orebfuscator#5]
There are some blocks missing from the extra transparency lists like sandstone walls that cause random blocks to appear under or behind them. These lists have to be manually updated each time new blocks are added. 

Solution is to update this method in ConfigManager
```	
@SuppressWarnings("deprecation")
	private byte[] generateTransparentBlocks(int engineMode) {
		byte[] transparentBlocks = new byte[MaterialHelper.getMaxId() + 1];

		Arrays.stream(Material.values())
			.filter(material -> material.isBlock() && material.isTransparent())
			.forEach(material -> NmsInstance.get().getMaterialIds(material).forEach(id -> transparentBlocks[id] = 1));

		Arrays.stream(NmsInstance.get().getExtraTransparentBlocks())
			.forEach(material -> NmsInstance.get().getMaterialIds(material).forEach(id -> transparentBlocks[id] = 1));

		byte status = (byte) (engineMode == 1 ? 0 : 1);
		NmsInstance.get().getMaterialIds(Material.LAVA).stream().forEach(id -> transparentBlocks[id] = status);

		return transparentBlocks;
	}
```
Switch the isTransparent with isOccluding get rid of the ever growing extra transparency lists since this method already does that and then it is no longer deprecated. Also allows for more seamless updates since you no longer have to update the extra transparent blocks manually each time new blocks are added. 

The extraTransparentBlocks array that is located in NMSManager can just be removed if we are using isOccluding.

**Comment by NgLoader** [comment]
Thanks
I commit this soon in 4.4.7

**Comment by NgLoader** [comment]
Thanks, here is the [commit](https://github.com/TeamWuffy/Orebfuscator/pull/7/commits/8164f523dc0f40b1d77c318293d8f0073413c860)
