### ISSUE TITLE
Release 4.4.7

### ISSUE THREAD

**Issue by NgLoader** [NgLoader/Orebfuscator#6]
- [x] Redesign code

- [x] Add API support
- [x] Optimize code
- [x] Check block break event error when spamming
- [x] ArrayIndexOutOfBoundsException fix
- [x] Fix [issue](https://github.com/lishid/Orebfuscator/issues/204#issuecomment-48374455)

**Comment by Chevels** [comment]
Hi there !

Just to report that this bug is still present in 4.4.6 version: [https://github.com/lishid/Orebfuscator/issues/204#issuecomment-483744558](url)

It is completely random and despite many tests it is very difficult to reproduce voluntarily. Fortunately, this rarely happens, but when it does, you have to reboot the server to stop this bug.
I have given more detail and clientside crash reports in my link.

Thank you for your work :)

**Comment by NgLoader** [comment]
Thanks for the report
Please tell me your
- Server Version
- Client Version
- Plugins...

**Comment by Chevels** [comment]
Of course ! Sorry I forgot that... 
Here more infos:
**- serveur:** git-Spigot-56f8471-56118c6 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- latest client crash was on 1.14.4 client (on 1.14.4 server). For others, see crash reports provided in my previous link. (From memory the clients were in 1.13.2 and the server was then in 1.13.2)

**- Plugins (57):** HackedCore, EntityTrackerFixer, WDLCompanion, AttackSpeedRemover, PlaceholderAPI, NoFullBrightMining, PlugMan, EnchantmentLock, ForcedGrammar, LeaderHeadsRevamped, ConsoleSpamFix, EntityDetection, MobFarmManager, PermissionsBukkit, CheckNameHistory, RealPlugin, AntiGuest, ViaVersion, ViaBackwards, dynmap, Itemizer, WorldEdit, SAML, AdvancedReplay, AWD, NBTEditor, HackedServer, VillagerOptimiser, ClearLag, WorldBorder, Multiverse-Core, ProtocolLib, AsyncWorldEdit, RedstoneClockDetector, LimitPillagers, PacketWrapper, Vault, LogBlock, ClientStats, RealTeleporter, Item2Chat, LWC, WorldGuard, Spartan, PhatLoots, afkTerminator, PetMaster, Orebfuscator4, War, Essentials, SimplePrefix, JLib, CMI, EssentialsAntiBuild, EssentialsSpawn, WorldGuardExtraFlags, FreeAutoMessage

But I should point out that I had done a lot of testing months ago and that OFC alone was causing this bug. I seem to have given quite a bit of information here: [https://github.com/lishid/Orebfuscator/issues/204](url)
(I just saw that my previous link did not work, the one referring to the same topic. See comments from April 16)

Have a nice day !

**Comment by Chevels** [comment]
Sorry, I don't understand why my links don't work... Link is pointing the issue 204 on previous repo of OFC

**Comment by NgLoader** [comment]
I found it already and added it to 4.4.7 release

**Comment by NgLoader** [comment]
Did you tested this error without any other plugin?

**Comment by NgLoader** [comment]
Please test your error with the newest version 😃
@Chevels

**Comment by Chevels** [comment]
> Did you tested this error without any other plugin?

Of course, but same result...


> Please test your error with the newest version smiley

I installed newest version of OFC (4.4.7) few hours ago, but java.lang.ArrayIndexOutOfBoundsException: 256 error is still present:

[16:13:18] [Server thread/ERROR]: ChunkX = 291, chunkZ = 144
> [16:13:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 256
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMap.readSectionHeader(ChunkMap.java:331)
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMap.moveToNextSection(ChunkMap.java:301)
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMap.moveToNextLayer(ChunkMap.java:245)
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.chunkmap.ChunkMap.readNextBlock(ChunkMap.java:202)
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:164)
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:76)
> [16:13:18] [Server thread/WARN]: at com.lishid.orebfuscator.hook.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:134)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
> [16:13:18] [Server thread/WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:185)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:155)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1394)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1367)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:1628)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:1096)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:745)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:964)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:497)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:472)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInTeleportAccept.a(SourceFile:31)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInTeleportAccept.a(SourceFile:8)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
> [16:13:18] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819)
> [16:13:18] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748) 

For the other error (client crash and prevent reconnection) I don't know for the moment, I've to wait and see because this issue rarely happend.

**Comment by Chevels** [comment]
> Please test your error with the newest version smiley

Bad news... This error happened today with newest version of OFC:

> 
> [16:36:06] [Server thread/INFO]: Alikss issued server command: /home v
> [16:36:06] [Server thread/ERROR]: ChunkX = 291, chunkZ = 142
> [16:36:06] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
> [16:36:06] [Server thread/ERROR]: ChunkX = 291, chunkZ = 144
> [16:36:06] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
> [16:36:09] [Server thread/INFO]: Alikss lost connection: Disconnected
> [16:36:09] [Server thread/INFO]: Alikss left the game

After that the player could no longer reconnect since the same error occurred in a loop. Here the crash-report (clientside):
[crash-2019-12-30_16.37.53-client.txt](https://github.com/TeamWuffy/Orebfuscator/files/4010899/crash-2019-12-30_16.37.53-client.txt)

**Comment by NgLoader** [comment]
I'm sorry but i can't reproduce you're error, you could try to update you're optifine version and server version if that helps

**Comment by NgLoader** [comment]
@Chevels I commit soon the 5.0.0 version with a new hash algorithmus and some performace boosts

**Comment by Chevels** [comment]
Hello,

Any news for 5.0.0 version ?
