### ISSUE TITLE
Orebfuscator v4.4.7 crashes on Paper 1.15.2

### ISSUE THREAD

**Issue by DmitryRendov** [NgLoader/Orebfuscator#9]
**Please fill out the following information:**
* Server Version: git-Paper-77 (MC: 1.15.2)
* Orebfuscator Version: v4.4.7
* Protocollib Version: v4.5.0

**Describe the bug**
Right after any player log in to the server it crashes.
https://pastebin.com/6fUcCf5w

**Comment by NgLoader** [comment]
I am currently unable to reproduce this error.
We are currently working on a new improved version which you can check out [here](https://github.com/Imprex-Development/Orebfuscator).

PS: this is not a full support/working version! It is still under development

**Comment by NgLoader** [comment]
This project is now achived and was moved to [Imprex-Development](https://github.com/Imprex-Development/Orebfuscator)
